name: dart_nvim_api
description: A Neovim API for Dart allowing for communication between a Neovim instance and a Dart program. Can be used for creating Neovim plugins, Neovim frontend GUIs, etc.
version: 0.1.4
homepage: https://github.com/smolck/dart-nvim-api

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  msgpack_dart: ^0.0.6
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
